/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/core/BaseButton.vue')['default']
    BaseButtonFiltr: typeof import('./components/core/BaseButtonFiltr.vue')['default']
    BaseIcon: typeof import('./components/core/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/core/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/core/BaseSelect.vue')['default']
    BaseSelectFaq: typeof import('./components/core/BaseSelectFaq.vue')['default']
    Bonus: typeof import('./components/Card/Bonus.vue')['default']
    CodeInput: typeof import('./components/core/CodeInput.vue')['default']
    CountBlock: typeof import('./components/CountBlock.vue')['default']
    Direction: typeof import('./components/Card/Direction.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    File: typeof import('./components/core/File.vue')['default']
    'File copy': typeof import('./components/core/File copy.vue')['default']
    FileOther: typeof import('./components/core/FileOther.vue')['default']
    'FileOther copy': typeof import('./components/core/FileOther copy.vue')['default']
    General: typeof import('./components/Card/General.vue')['default']
    HeadBlock: typeof import('./components/HeadBlock.vue')['default']
    HeadBlockProfile: typeof import('./components/HeadBlockProfile.vue')['default']
    Index: typeof import('./components/Stories/Index.vue')['default']
    Item: typeof import('./components/Stories/Item.vue')['default']
    LazyOnView: typeof import('./components/LazyOnView.vue')['default']
    NoInt: typeof import('./components/NoInt.vue')['default']
    Preloader: typeof import('./components/Preloader.vue')['default']
    Raffle: typeof import('./components/Card/Raffle.vue')['default']
    Review: typeof import('./components/Card/Review.vue')['default']
    Review2: typeof import('./components/Card/Review2.vue')['default']
    ReviewPopup: typeof import('./components/ReviewPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./components/Slider.vue')['default']
    SliderHotels: typeof import('./components/SliderHotels.vue')['default']
    SliderServices: typeof import('./components/SliderServices.vue')['default']
    Star: typeof import('./components/Star.vue')['default']
    Star2: typeof import('./components/Star2.vue')['default']
    Status: typeof import('./components/Card/Status.vue')['default']
    StoriesGroupSlider: typeof import('./components/Stories/Group/StoriesGroupSlider.vue')['default']
    StoriesMainSlider: typeof import('./components/Stories/Main/StoriesMainSlider.vue')['default']
    StoriesMainWrapper: typeof import('./components/Stories/Main/StoriesMainWrapper.vue')['default']
    StoriesMenu: typeof import('./components/Stories/Menu/StoriesMenu.vue')['default']
    StoriesMenuSlider: typeof import('./components/Stories/Menu/StoriesMenuSlider.vue')['default']
    SupportPopup: typeof import('./components/SupportPopup.vue')['default']
    TabBody: typeof import('./components/core/TabBody.vue')['default']
    TabContent: typeof import('./components/core/TabContent.vue')['default']
    TabItem: typeof import('./components/core/TabItem.vue')['default']
    TabItemList: typeof import('./components/core/TabItemList.vue')['default']
    TopBlock: typeof import('./components/core/TopBlock.vue')['default']
    Upcoming: typeof import('./components/Card/Upcoming.vue')['default']
    VerifyMail: typeof import('./components/VerifyMail.vue')['default']
    VerifyPhone: typeof import('./components/VerifyPhone.vue')['default']
  }
}
